export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_MATCHES_LIST_REQUEST = "USER_MATCHES_LIST_REQUEST";
export const USER_MATCHES_LIST_SUCCESS = "USER_MATCHES_LIST_SUCCESS";
export const USER_MATCHES_LIST_FAIL = "USER_MATCHES_LIST_FAIL";

export const USER_ADD_MATCH_REQUEST = "USER_ADD_MATCH_REQUEST";
export const USER_ADD_MATCH_SUCCESS = "USER_ADD_MATCH_SUCCESS";
export const USER_ADD_MATCH_FAIL = "USER_ADD_MATCH_FAIL";

export const USER_DELETE_MATCH_REQUEST = "USER_DELETE_MATCH_REQUEST";
export const USER_DELETE_MATCH_SUCCESS = "USER_DELETE_MATCH_SUCCESS";
export const USER_DELETE_MATCH_FAIL = "USER_DELETE_MATCH_FAIL";

export const USER_LIKES_LIST_REQUEST = "USER_LIKES_LIST_REQUEST";
export const USER_LIKES_LIST_SUCCESS = "USER_LIKES_LIST_SUCCESS";
export const USER_LIKES_LIST_FAIL = "USER_LIKES_LIST_FAIL";

export const USER_ADD_LIKE_REQUEST = "USER_ADD_LIKE_REQUEST";
export const USER_ADD_LIKE_SUCCESS = "USER_ADD_LIKE_SUCCESS";
export const USER_ADD_LIKE_FAIL = "USER_ADD_LIKE_FAIL";

export const USER_DELETE_LIKE_REQUEST = "USER_DELETE_LIKE_REQUEST";
export const USER_DELETE_LIKE_SUCCESS = "USER_DELETE_LIKE_SUCCESS";
export const USER_DELETE_LIKE_FAIL = "USER_DELETE_LIKE_FAIL";

export const USER_NOTIFICATIONS_REQUEST = "USER_NOTIFICATIONS_REQUEST";
export const USER_NOTIFICATIONS_SUCCESS = "USER_NOTIFICATIONS_SUCCESS";
export const USER_NOTIFICATIONS_FAIL = "USER_NOTIFICATIONS_FAIL";

export const USER_MESSAGES_REQUEST = "USER_MESSAGES_REQUEST";
export const USER_MESSAGES_SUCCESS = "USER_MESSAGES_SUCCESS";
export const USER_MESSAGES_FAIL = "USER_MESSAGES_FAIL";

export const USER_NEW_MESSAGES_REQUEST = "USER_NEW_MESSAGES_REQUEST";
export const USER_NEW_MESSAGES_SUCCESS = "USER_NEW_MESSAGES_SUCCESS";
export const USER_NEW_MESSAGES_FAIL = "USER_NEW_MESSAGES_FAIL";

export const USER_SEND_MESSAGE_REQUEST = "USER_SEND_MESSAGE_REQUEST";
export const USER_SEND_MESSAGE_SUCCESS = "USER_SEND_MESSAGE_SUCCESS";
export const USER_SEND_MESSAGE_FAIL = "USER_SEND_MESSAGE_FAIL";

export const USER_UNREAD_NOTIFICATIONS_REQUEST =
  "USER_UNREAD_NOTIFICATIONS_REQUEST";
export const USER_UNREAD_NOTIFICATIONS_SUCCESS =
  "USER_UNREAD_NOTIFICATIONS_SUCCESS";
export const USER_UNREAD_NOTIFICATIONS_FAIL = "USER_UNREAD_NOTIFICATIONS_FAIL";
